# Generated by Django 4.2.2 on 2023-06-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=50)),
                ('content', models.CharField(db_column='content', max_length=1000)),
                ('creation_date', models.DateTimeField(db_column='creation_date')),
                ('author', models.CharField(db_column='author', max_length=1000)),
            ],
        ),
    ]
